"""Add has_photo to User

Revision ID: 07a72ca088fd
Revises: e83061317af2
Create Date: 2026-09-21 11:58:03.630076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a72ca088fd'
down_revision: Union[str, None] = 'e83061317af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pms_bills')
    op.drop_table('pms_users')
    op.drop_table('pms_patients')
    op.drop_table('pms_payments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_photo', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_photo')

    op.create_table('pms_payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('razorpay_signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('CREATED', 'SUCCESS', 'FAILED', name='pms_payments_payment_status_enum'), server_default=sa.text("'CREATED'::pms_payments_payment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['pms_bills.id'], name='FK_1839b79ea730550bb07b69628b9', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_c59c8c641bc5fceb70415f78225')
    )
    op.create_table('pms_patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='pms_patients_gender_enum'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_f343862b877c1f2a2b9e98b81e3'),
    sa.UniqueConstraint('email', name='UQ_4389911b057725b88954a1d939a'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pms_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_45e393b966249008f206ba50b2e'),
    sa.UniqueConstraint('email', name='UQ_c467d62edb1ed98fdd9325b5e61')
    )
    op.create_table('pms_bills',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='pms_bills_payment_status_enum'), server_default=sa.text("'PENDING'::pms_bills_payment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['pms_patients.id'], name='FK_02c28a3f4ce6125accaa0c0f399', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_12298bdcfcb4ea79ebc34a5f8b6')
    )
    # ### end Alembic commands ###
