"""Update schema

Revision ID: 1cd9aca4c349
Revises: 7c1020740449
Create Date: 2026-08-05 14:30:53.017691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd9aca4c349'
down_revision: Union[str, None] = '7c1020740449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limits_identifier'), ['identifier'], unique=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='learner_id::integer')
        batch_op.create_foreign_key(None, 'users', ['learner_id'], ['id'])

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='learner_id::integer')
        batch_op.create_unique_constraint('uq_progress_learner_course', ['learner_id', 'course_id'])
        batch_op.create_foreign_key(None, 'users', ['learner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_progress_learner_course', type_='unique')
        batch_op.alter_column('learner_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('learner_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limits_identifier'))

    op.drop_table('rate_limits')
    op.drop_table('certificate_sequences')
    # ### end Alembic commands ###
