"""migrate_pk_to_uuid

Revision ID: 224b429db984
Revises: 1cd9aca4c349
Create Date: 2026-08-11 18:17:40.634832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224b429db984'
down_revision: Union[str, None] = '1cd9aca4c349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    queries = [
        "ALTER TABLE assessment_approvals DROP CONSTRAINT IF EXISTS assessment_approvals_learner_id_fkey",
        "ALTER TABLE assessment_approvals DROP CONSTRAINT IF EXISTS assessment_approvals_attempt_id_fkey",
        "ALTER TABLE attempts DROP CONSTRAINT IF EXISTS attempts_learner_id_fkey",
        "ALTER TABLE certificates DROP CONSTRAINT IF EXISTS certificates_learner_id_fkey",
        "ALTER TABLE enrollments DROP CONSTRAINT IF EXISTS enrollments_learner_id_fkey",
        "ALTER TABLE enrollments DROP CONSTRAINT IF EXISTS enrollments_assigned_by_fkey",
        "ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey",
        "ALTER TABLE progress DROP CONSTRAINT IF EXISTS progress_learner_id_fkey",
        "ALTER TABLE progress DROP CONSTRAINT IF EXISTS uq_progress_learner_course",
        "ALTER TABLE enrollments DROP CONSTRAINT IF EXISTS uq_enrollment_learner_course",
    ]
    
    tables = ['users', 'questions', 'chapter_questions', 'progress', 'certificate_sequences', 'enrollments', 'attempts', 'sync_logs', 'notifications', 'assessment_approvals', 'rate_limits']
    
    for table in tables:
        queries.append(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT")
        queries.append(f"ALTER TABLE {table} ALTER COLUMN id TYPE VARCHAR USING id::VARCHAR")

    fk_alters = [
        "ALTER TABLE assessment_approvals ALTER COLUMN learner_id TYPE VARCHAR USING learner_id::VARCHAR",
        "ALTER TABLE assessment_approvals ALTER COLUMN attempt_id TYPE VARCHAR USING attempt_id::VARCHAR",
        "ALTER TABLE attempts ALTER COLUMN learner_id TYPE VARCHAR USING learner_id::VARCHAR",
        "ALTER TABLE certificates ALTER COLUMN learner_id TYPE VARCHAR USING learner_id::VARCHAR",
        "ALTER TABLE enrollments ALTER COLUMN learner_id TYPE VARCHAR USING learner_id::VARCHAR",
        "ALTER TABLE enrollments ALTER COLUMN assigned_by TYPE VARCHAR USING assigned_by::VARCHAR",
        "ALTER TABLE notifications ALTER COLUMN user_id TYPE VARCHAR USING user_id::VARCHAR",
        "ALTER TABLE progress ALTER COLUMN learner_id TYPE VARCHAR USING learner_id::VARCHAR",
    ]
    queries.extend(fk_alters)

    queries.extend([
        "ALTER TABLE assessment_approvals ADD CONSTRAINT assessment_approvals_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES users(id)",
        "ALTER TABLE assessment_approvals ADD CONSTRAINT assessment_approvals_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES attempts(id)",
        "ALTER TABLE attempts ADD CONSTRAINT attempts_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES users(id)",
        "ALTER TABLE certificates ADD CONSTRAINT certificates_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES users(id)",
        "ALTER TABLE enrollments ADD CONSTRAINT enrollments_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES users(id)",
        "ALTER TABLE enrollments ADD CONSTRAINT enrollments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users(id)",
        "ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)",
        "ALTER TABLE progress ADD CONSTRAINT progress_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES users(id)",
        "ALTER TABLE progress ADD CONSTRAINT uq_progress_learner_course UNIQUE (learner_id, course_id)",
        "ALTER TABLE enrollments ADD CONSTRAINT uq_enrollment_learner_course UNIQUE (learner_id, course_id)",
    ])
    
    for query in queries:
        op.execute(query)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('assigned_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('learner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('chapter_questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('certificate_sequences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('learner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('attempts_id_seq'::regclass)"))

    with op.batch_alter_table('assessment_approvals', schema=None) as batch_op:
        batch_op.alter_column('attempt_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('learner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
