"""add_assessment_approvals

Revision ID: 670b8f64ac76
Revises: 163373219f68
Create Date: 2026-08-03 14:34:03.782851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670b8f64ac76'
down_revision: Union[str, None] = '163373219f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_approvals_approval_token_key', 'assessment_approvals', type_='unique')
    op.create_index(op.f('ix_assessment_approvals_approval_token'), 'assessment_approvals', ['approval_token'], unique=True)
    op.create_index(op.f('ix_assessment_approvals_course_id'), 'assessment_approvals', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessment_approvals_learner_id'), 'assessment_approvals', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_approvals_learner_id'), table_name='assessment_approvals')
    op.drop_index(op.f('ix_assessment_approvals_course_id'), table_name='assessment_approvals')
    op.drop_index(op.f('ix_assessment_approvals_approval_token'), table_name='assessment_approvals')
    op.create_unique_constraint('assessment_approvals_approval_token_key', 'assessment_approvals', ['approval_token'])
    # ### end Alembic commands ###
