"""course max_attempts

Revision ID: 6a000f16dba3
Revises: ed508e222628
Create Date: 2026-07-23 10:43:34.850653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a000f16dba3'
down_revision: Union[str, None] = 'ed508e222628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('max_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'max_attempts')
    # ### end Alembic commands ###
