"""add_vessel_master_to_orientation_enrollment

Revision ID: 74e5dd77b6b1
Revises: 8221c1ca149d
Create Date: 2026-09-10 17:45:49.084981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e5dd77b6b1'
down_revision: Union[str, None] = '8221c1ca149d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vessel_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('master_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_enrollments', schema=None) as batch_op:
        batch_op.drop_column('master_name')
        batch_op.drop_column('vessel_name')

    # ### end Alembic commands ###
