"""course target audience

Revision ID: 7c1020740449
Revises: 670b8f64ac76
Create Date: 2026-08-04 14:54:08.399221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1020740449'
down_revision: Union[str, None] = '670b8f64ac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('target_ranks', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('target_users', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'target_users')
    op.drop_column('courses', 'target_ranks')
    # ### end Alembic commands ###
