"""orientation program

Revision ID: 8221c1ca149d
Revises: 16bf66fb3642
Create Date: 2026-09-10 15:28:38.461690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8221c1ca149d'
down_revision: Union[str, None] = '16bf66fb3642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orientation_programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('from_rank', sa.String(), nullable=True),
    sa.Column('to_rank', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orientation_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['orientation_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orientation_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orientation_enrollments_learner_id'), ['learner_id'], unique=False)

    op.create_table('orientation_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['orientation_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orientation_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['orientation_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orientation_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orientation_submissions_enrollment_id'), ['enrollment_id'], unique=False)

    op.create_table('orientation_task_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('proof_path', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['orientation_enrollments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['orientation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'task_id', name='uq_orientation_completion')
    )
    with op.batch_alter_table('orientation_task_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orientation_task_completions_enrollment_id'), ['enrollment_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_vessel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approver_department', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approver_department')
        batch_op.drop_column('approver_vessel')

    with op.batch_alter_table('orientation_task_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orientation_task_completions_enrollment_id'))

    op.drop_table('orientation_task_completions')
    with op.batch_alter_table('orientation_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orientation_submissions_enrollment_id'))

    op.drop_table('orientation_submissions')
    op.drop_table('orientation_tasks')
    with op.batch_alter_table('orientation_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orientation_enrollments_learner_id'))

    op.drop_table('orientation_enrollments')
    op.drop_table('orientation_programs')
    # ### end Alembic commands ###
