"""chapter kind and quiz questions

Revision ID: 8a1c2f9e4b3d
Revises: fd98cac51914
Create Date: 2026-07-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1c2f9e4b3d'
down_revision: Union[str, None] = 'fd98cac51914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('kind', sa.String(), server_default='lesson', nullable=False))
    op.create_table('chapter_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_questions_chapter_id'), 'chapter_questions', ['chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_questions_chapter_id'), table_name='chapter_questions')
    op.drop_table('chapter_questions')
    op.drop_column('chapters', 'kind')
    # ### end Alembic commands ###
