"""smartpal sync fields and synclog

Revision ID: c2e7a9f1d5b6
Revises: 8a1c2f9e4b3d
Create Date: 2026-07-25 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e7a9f1d5b6'
down_revision: Union[str, None] = '8a1c2f9e4b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emp_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emp_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_vessel', sa.String(), nullable=True))
    op.add_column('users', sa.Column('seamen_book_no', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_place', sa.String(), nullable=True))
    op.add_column('users', sa.Column('smartpal_synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_emp_id'), 'users', ['emp_id'], unique=True)

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_users_emp_id'), table_name='users')
    op.drop_column('users', 'smartpal_synced_at')
    op.drop_column('users', 'birth_place')
    op.drop_column('users', 'seamen_book_no')
    op.drop_column('users', 'current_vessel')
    op.drop_column('users', 'emp_status')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'emp_id')
    # ### end Alembic commands ###
