"""add_requires_proof_to_orientation_task

Revision ID: cf24b050da4f
Revises: 74e5dd77b6b1
Create Date: 2026-09-10 21:20:13.089790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf24b050da4f'
down_revision: Union[str, None] = '74e5dd77b6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_proof', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_tasks', schema=None) as batch_op:
        batch_op.drop_column('requires_proof')

    # ### end Alembic commands ###
