"""add_sign_on_relief_dates_to_users

Revision ID: d4fbd63fb37e
Revises: b2d4e8f1a3c7
Create Date: 2026-09-11 13:05:00.004298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fbd63fb37e'
down_revision: Union[str, None] = 'b2d4e8f1a3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_on_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('relief_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('relief_date')
        batch_op.drop_column('sign_on_date')

    # ### end Alembic commands ###
