"""add tab_switch_count to screening_attempts

Revision ID: e6d48fbd2878
Revises: 52ce096f1891
Create Date: 2026-09-01 17:14:42.276511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d48fbd2878'
down_revision: Union[str, None] = '52ce096f1891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_switch_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_attempts', schema=None) as batch_op:
        batch_op.drop_column('tab_switch_count')

    # ### end Alembic commands ###
