"""revert_certificate_sequence_to_integer

Revision ID: e7400cbacbf4
Revises: 224b429db984
Create Date: 2026-08-12 10:30:51.556999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7400cbacbf4'
down_revision: Union[str, None] = '224b429db984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM certificate_sequences WHERE id ~ '[a-zA-Z]'")
    op.execute("ALTER TABLE certificate_sequences ALTER COLUMN id TYPE INTEGER USING id::integer")
    
    # Check if the sequence exists, if not create it
    op.execute("CREATE SEQUENCE IF NOT EXISTS certificate_sequences_id_seq")
    
    # Set the column to use the sequence
    op.execute("ALTER TABLE certificate_sequences ALTER COLUMN id SET DEFAULT nextval('certificate_sequences_id_seq')")
    
    # Update the sequence to the maximum existing ID just in case
    op.execute("SELECT setval('certificate_sequences_id_seq', COALESCE((SELECT MAX(id) FROM certificate_sequences), 1))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_sequences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
