"""per_task_status_and_rejection

Revision ID: e83061317af2
Revises: a064f726a87d
Create Date: 2026-09-20 11:53:22.326211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e83061317af2'
down_revision: Union[str, None] = 'a064f726a87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_task_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rejection_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orientation_task_completions', schema=None) as batch_op:
        batch_op.drop_column('rejection_note')
        batch_op.drop_column('status')


    # ### end Alembic commands ###
